language: go

go:
  - tip
    
before_install:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  
script:
  - go build ./...
  - ./ci/check_go_fmt.sh
  
  - go test . -v -coverprofile=pbar.coverfile
  - go test ./render/ -v -coverprofile=render.coverprofile
  
  - $GOPATH/bin/gover
  - $GOPATH/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
